name = "kingshark386"
license = "MIT"

licenselink = "https://github.com/kingshark8848/kingshark386-hugo-theme/blob/master/LICENSE.md"
description = "kingshark386 -- a 386/8bit/pixel style theme for Hugo."

homepage = "https://github.com/kingshark8848/kingshark386-hugo-theme"
tags = ["hugo", "theme", "386", "pixel", "dark"]
features = ["blog","profile"]
min_version = 0.1

[author]
    name = "Xiao Wang"
    homepage = "https://www.kingsharkworld.com/"
